require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
permissions_path = '../node_modules/react-native-permissions/ios'
platform :ios, '10.0'

target 'SimformPractical' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'SimformPracticalTests' do
    inherit! :complete
    # Pods for testing
  end
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'SimformPractical-tvOS' do
  # Pods for SimformPractical-tvOS

  target 'SimformPractical-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
