const FETCH_SUCCESS = "FETCH_SUCCESS";
const FETCH_ERROR = "FETCH_ERROR";

export const FETCH_FAILED = "FETCH_FAILED";
export const UN_AUTHORISED = "UN_AUTHORISED";
export const NOT_FOUND = "PAGE_NOT_FOUND";
export const NOT_ACTIVATED = "NOT_ACTIVATED";
export const SHOW_LOADER = "SHOW_LOADER";
export const SEARCH_LOADER = "SEARCH_LOADER";
export const CURRENT_API = "CURRENT_API";



const GET_VIDEO = "GET_VIDEO";
export const GET_VIDEO_FETCH = GET_VIDEO;
export const GET_VIDEO_FETCH_SUCCESS = GET_VIDEO_FETCH + "_" + FETCH_SUCCESS;
export const GET_VIDEO_FETCH_ERROR = GET_VIDEO_FETCH + "_" + FETCH_ERROR;


const GET_STRIP = "GET_STRIP";
export const GET_STRIP_FETCH = GET_STRIP;
export const GET_STRIP_FETCH_SUCCESS = GET_STRIP_FETCH + "_" + FETCH_SUCCESS;
export const GET_STRIP_FETCH_ERROR = GET_STRIP_FETCH + "_" + FETCH_ERROR;

// Logout

const LOGOUT = "LOGOUT";
export const LOGOUT_FETCH = LOGOUT;
